GET https://www.taptap.com/webapiv2/config/v1/terms?page_referer=https:%2F%2Fwww.baidu.com%2Flink%3Furl%3DdJ-GIH_AmFtdJnloccCenNkv-7XaUNurNgsa4_xl7HFxaJ2XCf_P_UnTYN-GvypS%26wd%3D%26eqid%3Dc4f5007a000336650000000361ea6ffd&page_path=%2Fapp%2F165287&X-UA=V%3D1%26PN%3DWebApp%26LANG%3Dzh_CN%26VN_CODE%3D59%26VN%3D0.1.0%26LOC%3DCN%26PLT%3DPC%26DS%3DAndroid%26UID%3D2cd0f8e0-7146-4bf9-8277-00673baea218%26DT%3DPC
Accept: application/json

###
